sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.24.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose -f local.yml  up -d --build

script:
  - docker-compose -f local.yml run django pytest
  - docker-compose -f local.yml run django black pastebin
  - docker-compose -f local.yml run django flake8 pastebin
  - make -C docs/ html
  - touch docs/_build/html/.nojekyll

after_script:
  - docker-compose down

deploy:
  - provider: pages:git
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./docs/build/html/
    keep_history: true
