# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build docker images
          command: docker-compose -f local.yml build
      - run:
          name: Run tests
          command: |
            docker-compose -f local.yml run django pytest --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports
  docs-build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements/local.txt
      - run:
          name: Build docs
          command: cd docs/ && make html
      - persist_to_workspace:
          root: docs/_build
          paths: html
  docs-deploy:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements/local.txt
      - run:
          name: Deploy docs to Github Pages
          command: cd docs/ && make github
workflows:
  version: 2
  build:
    jobs:
      - build
      - docs-build
      - docs-deploy:
          requires:
            - build
            - docs-build
          filters:
            branches:
              only: master
