# Generated by Django 2.2.6 on 2019-10-29 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0003_auto_20191029_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_pastes', to=settings.AUTH_USER_MODEL),
        ),
    ]
